IF(NOT CMAKE_ASM_COMPILE_OBJECT)
  IF(UNIX)
    SET(CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> -f elf <FLAGS> -o <OBJECT> <SOURCE>")
  ELSE(UNIX)
    SET(CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> -f win32 -DWIN32 <FLAGS>  -o <OBJECT> <SOURCE>")
  ENDIF(UNIX)
ENDIF(NOT CMAKE_ASM_COMPILE_OBJECT)

SET(CMAKE_ASM_INFOMATION_LOADED 1)