#!/bin/tcsh

#setup for CodeWarrior
if (-d build) then
  echo "CodeWarrior build directory already exists. Done."
else
  echo "CodeWarrior build directory does not exist. Creating framework structure..."
  tar zxf osx_build_dir.tgz
endif
